name: azul_video_editor
description: "A lightweight Flutter plugin for video editing without FFmpeg dependency. Trim, merge, adjust speed and more on Android & iOS."
version: 0.0.2
homepage: https://github.com/azulmouad/azul_video_editor
repository: https://github.com/azulmouad/azul_video_editor
issue_tracker: https://github.com/azulmouad/azul_video_editor/issues
funding:
  - https://buymeacoffee.com/moaddevlop9
topics:
  - video-editor
  - video-processing
  - video-trimming
  - video-compression
  - video-cropping

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  easy_video_editor: ^0.0.5
  video_player: ^2.9.5
  #video_thumbnail: ^0.5.3
  flutter_video_thumbnail_plus: ^1.0.5
  path: ^1.9.0
  flutter_soloud:
    path: D:/GIT/GitHub/flutter_soloud
    # Local copy of commit 28435a2bda6c0685b98d1fb5846471bd071ac925
  path_provider: ^2.1.5
  ffmpeg_kit_flutter_new_audio: ^1.1.0
  audio_metadata_reader: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
